server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:15432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    user: postgres
    password: postgres
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://192.168.99.100:15432/postgres
jwt:
  token:
    secret: verycomplexsecret
    expired: 3600000
